name: svdp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=2.16=mkl
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2020.2=256
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy=1.21.6=py37h976b520_0
  - olefile=0.47=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - terminaltables=3.1.10=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - attr==0.3.1
      - attrs==23.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.0.0
      - cachetools==5.3.2
      - cffi==1.15.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - easydict==1.10
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - exceptiongroup==1.0.4
      - fastjsonschema==2.16.2
      - filelock==3.9.0
      - fonttools==4.38.0
      - ftfy==6.1.1
      - gdown==4.6.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - google-images-download==2.8.0
      - grpcio==1.51.1
      - h11==0.14.0
      - h5py==3.7.0
      - huggingface-hub==0.11.1
      - hydra-core==1.3.1
      - idna==3.6
      - imageio==2.25.0
      - importlib-metadata==6.7.0
      - importlib-resources==5.10.2
      - iopath==0.1.9
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==7.4.8
      - jupyter-core==4.12.0
      - jupyter-server==1.23.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.5
      - kornia==0.6.9
      - llvmlite==0.39.1
      - lpips==0.1.4
      - lxml==4.9.2
      - markdown==3.4.1
      - markdown-it-py==2.1.0
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==2.0.4
      - mmcv-full==1.7.1
      - model-index==0.1.11
      - mss==7.0.1
      - mypy-extensions==0.4.3
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.7
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - networkx==2.6.3
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - notifyemail==1.0.2
      - numba==0.56.4
      - numpy-quaternion==2022.4.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open3d==0.9.0.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.9.0.80
      - openmim==0.3.6
      - openpyxl==3.0.10
      - ordered-set==4.1.0
      - outcome==1.2.0
      - packaging==23.2
      - pandas==1.3.5
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.10.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - portalocker==2.7.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.43
      - protobuf==4.24.4
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.3.1
      - rsa==4.9
      - scipy==1.7.3
      - selenium==4.11.2
      - send2trash==1.8.2
      - sentry-sdk==1.40.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - terminado==0.17.1
      - timm==0.4.5
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - trio==0.22.2
      - trio-websocket==0.11.1
      - urllib3==2.0.7
      - wandb==0.16.2
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - widgetsnbextension==4.0.9
      - wsproto==1.2.0
      - yapf==0.40.2
      - zipp==3.15.0
prefix: /home/jonaslei/miniconda3/envs/svdp
